### ISSUE TITLE
FIle Manager > Terminal emulator is emty "For large screens" or "For small screens"

### ISSUE THREAD

**Issue by pol2095** [RPi-Distro/repo#375] opened 2024-07-18 20:38 UTC
Hello,

on Raspberry Pi OS BookWorm, when I change the scaling (Raspberry > Preferences > Appearance Settings > Default) to "For large screens" or "For small screens", `File Manager > Edit > Preferences > Terminal emulator` is emty

"For medium screens" :
![Medium_screens](https://github.com/user-attachments/assets/81a16390-acf9-48ef-9e59-7b18b7bfe478)

"For large screens" or "For small screens" :
![Large_screens](https://github.com/user-attachments/assets/1440f7dc-082b-451c-9671-aa40274b7621)

This causes problems, for example I have an app that return when I try to launch it :
![Sans titre](https://github.com/user-attachments/assets/4faec9fb-5dbc-4a8e-972c-aae8a2ab8af9)
when I click on `Execute` the app work fine,
but when I click on `Execute in Terminal`, I have the message error :
```
Failed to execute child process "xterm" (No such file or directory)
```

and I use the file explorer to select a folder. I then right click and select "Open in Terminal".
I get this error:
`Terminal emulator is not set`

Thanks

**Comment by XECDesign** [comment] 2024-07-22 08:51
Duplicate of https://github.com/raspberrypi/bookworm-feedback/issues/278

**Closed as not planned by XECDesign** 2024-07-22 08:51 UTC
