### ISSUE TITLE
[Bullseye] Imagemagick convert utility results in Illegal instruction

### ISSUE THREAD

**Issue by darksidelemm** [RPi-Distro/repo#372] opened 2024-06-27 08:58 UTC
I'm debugging an issue on a Raspberry Pi Zero W, using the imagemagick 'convert' utility. Currently this is occurring on a machine run by someone else, so apologies for the screenshots. I hope to replicate this when I'm back from a work trip and can access a RPi Zero W myself.

Platform: Raspberry Pi Zero W v1.1, running Bullseye. Kernel 6.1.21, armv6l

Essentially, when it's run, sometimes it breaks with an Illegal Instruction error:
![41a45cd5-c561-433f-8f95-508261400c9e](https://github.com/RPi-Distro/repo/assets/1040275/3c15cdc5-86fe-4381-8527-feaa7ce50996)

I was a bit confused by this so confirmed what package they were using:
![f4d06439-b06a-4a27-8fa4-a681d68e4929](https://github.com/RPi-Distro/repo/assets/1040275/036f9f39-fd6b-40ee-8e64-64ca9e153a4b)

I've read elsewhere that this kind of problem can be from an armv7 package being used on an armv6 system. Apparently armhf means different things in raspbian and debian worlds?

Anyway. I compared the MD5sum of the packages from raspbian and debian:
raspbian: http://raspbian.raspberrypi.org/raspbian/pool/main/i/imagemagick/imagemagick_6.9.11.60+dfsg-1.3+deb11u3_armhf.deb
debian: http://security.debian.org/debian-security/pool/updates/main/i/imagemagick/imagemagick_6.9.11.60+dfsg-1.3+deb11u3_armhf.deb
Both have the same md5sum of 7d717709b5519047c3649296dadb2d4e

**Is this right? Should these packages be the same?**

I'm hoping to replicate this issue and do a bit more debugging when I can get access to a RPi Zero W next.

**Comment by XECDesign** [comment] 2024-07-03 11:38
I wouldn't have expected them to have the exact same checksums, but debian is aiming for reproducible builds, so it's not too surprising. I'll have a quick look to see if there's anything obviously wrong, but this looks more like a [Raspbian issue](https://bugs.launchpad.net/raspbian/+bugs).

**Comment by darksidelemm** [comment] 2024-07-03 11:42
Apologies if this was the wrong place to post this!  If this is the wrong place, I can post it on the raspbian bug tracker you linked...

I've also heard that Illegal Instruction errors can occur when the RPis overheat, and that underclocking can help reduce how often this occurs. Hopefully this ends up just being some kind of overheating bug, but I was wondering about the armv6 vs armv7 stuff...

**Comment by XECDesign** [comment] 2024-07-08 16:51
What format are you converting to/from? I just tried it out and it seemed to work

```
 $ cat /proc/device-tree/model; echo; uname -a
Raspberry Pi Zero W Rev 1.1
Linux serge-zerotest 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l GNU/Linux
$ apt policy imagemagick
imagemagick:
  Installed: 8:6.9.11.60+dfsg-1.3+deb11u3
  Candidate: 8:6.9.11.60+dfsg-1.3+deb11u3
  Version table:
 *** 8:6.9.11.60+dfsg-1.3+deb11u3 500
        500 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages
        100 /var/lib/dpkg/status
$ convert 2024-07-08-132736_1920x1080_scrot.png out.jpg
$ file out.jpg
out.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 1920x1080, components 3

```

**Comment by popcornmix** [comment] 2024-07-08 17:15
@darksidelemm can you try adding `over_voltage=2` to config.txt and reboot?

**Comment by XECDesign** [comment] 2024-07-16 13:39
Closing since it doesn't seem to be a repo issue.

**Closed as not planned by XECDesign** 2024-07-16 13:39 UTC
