### ISSUE TITLE
std::atomic is broken for 64 bit integers

### ISSUE THREAD

**Issue by rsalinas** [RPi-Distro/repo#117] opened 2018-11-19 16:33 UTC
The problem is still there. std::atomic<uint64_t> is not atomic.  It works well for 32 bits. 
This will seriously break consistency in some applications.

Tried on: gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1+deb9u1) 

Code showing the problem:
```
// Compile with:
//   g++ std-atomic-bug-RPi.cpp -pthread -o std::atomic-bug-RPi

#include <atomic>
#include <thread>
#include <cstdio>

int main(int argc, char **argv) {
    constexpr int itemsPerThread = 10000;
    constexpr int threadCount = 20;
    constexpr int idCount = itemsPerThread * threadCount;
    typedef uint64_t testedType;

    auto ids = new testedType[threadCount][itemsPerThread];
    std::thread threads[threadCount];
    std::atomic<testedType> atomicId{0};

    for (int th = 0; th < threadCount; th++) {
        threads[th] = std::thread([&, th]() {
            for (size_t i = 0; i < itemsPerThread; ++i) {
                ids[th][i] = atomicId++;
            }
        });
    }
    auto seenIds = new bool[threadCount*itemsPerThread]{};
    for (int i = 0; i < threadCount; i++) {
        threads[i].join();
        for (int j = 0; j < itemsPerThread; j++) {
            testedType id = ids[i][j];
            if (seenIds[id]) {
                fprintf(stderr, "Error: Your std::atomic is broken: %lu :(\n", id);
                exit(1);  // Forget the running threads
            }
            seenIds[id] = true;
        }
    }
    delete[] ids;
    fprintf(stderr, "Success :)\n");
}
```

**Comment by XECDesign** [comment] 2018-11-19 17:11
This repo is for issues for packages in archive.raspberrypi.org. Could you please report the issue to https://bugs.launchpad.net/raspbian ?

Duplicate of #103

**Closed** 2019-08-06 10:21 UTC
